[package]
name = "crypt2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-bip39 = "1.0.0"
rand = "0.8.5"
simple_crypt = "0.2.3"
base64 = "0.22.1"
bincode = "1.3.3"
